### ISSUE TITLE
error redeeming code: Post https://console.example.com/oauth/token: EOF

### ISSUE THREAD

**Issue by maxberndt1234** [openshift/oauth-proxy#106]
Hey,

I am trying to open Grafana from the openshift-monitoring project (shipped with openshift-ansible). Its a fresh 3.11 ODK cluster build with these playbooks: https://github.com/openshift/openshift-ansible.

Now in the openshift-monitoring project I see that a route was configured: https://grafana-openshift-monitoring.example.com . When I open that link, I get to the Log-In-with-OpenShift screen. I hit that button and get redirected to https://console.example.com/oauth/authorize?foo=bar . I authorize with my SSO and the side loads for while until a 500 Internal Error is shown.

In the logs of the grafana-proxy I see this error:

```
2019/03/07 08:37:37 oauthproxy.go:635: error redeeming code (client:10.13.10.1:48968): Post https://console.example.com/oauth/token: EOF
2019/03/07 08:37:37 oauthproxy.go:434: ErrorPage 500 Internal Error Internal Error
2019/03/07 08:37:37 provider.go:382: authorizer reason: no RBAC policy matched
```

Can you help me?

PS: The authorization in general works. I am able to authorize and access the dashboard at https://console.example.com. My user holds the role `cluster-monitoring-view`.

**Comment by Dimss** [comment]
@maxandersen I think `grafana-proxy` pod unable to execute API call to the K8S masters server. 
Make sure this address `console.example.com` is resolvable and accessible fro the `grafana-proxy` pod.
Please note, if the master server DNS name is not resolvable, Prometheus will not works either. 
To make a quick and dirty fix, you may update `/etc/hosts` file on your infra node (the one who running monitoring related pods) with IP and DNS name of one of your masters servers 

For example:
```
10.1.1.1 console.example.com # 10.1.1.1 is one of your master's IPs
```
**Do not forget to reboot your infra node.**
After reboot pods will come up and will be able resolve your console.example.com to 10.1.1.1

**Comment by maxandersen** [comment]
Different max :) @maxberndt1234

**Comment by maxberndt1234** [comment]
@Dimss, thanks for your support. I updated my master node and put a line in /etc/hosts : `127.0.0.1 console.example.com'.

Then I `oc rsh -c prometheus-proxy prometheus-k8s-0` into a container that runs on that master node (verified it runs there). From the prometheus-proxy container I issue `curl -v https://console.example.com` and get:

```
* About to connect() to console.example.com port 443 (#0)
*   Trying 127.0.0.1...
* Connection refused
```
Hence, its now resolvable from the proxy to the local ip (before it was the external ip), but nothing listens on that address:port.

**Comment by Dimss** [comment]
@maxberndt1234 what is IP of your master node? 
Is your master your `prometheus-proxy` pod is proxy running on the master node?

**Comment by maxberndt1234** [comment]
@Dimss my master has the local ip 172.31.136.180. yes, the pod is running on the master node (verified with `oc describe pod prometheus-k8s-0`

**Comment by Dimss** [comment]
alright, so the issue is that you are inside container, thus you can't resolve to 127.0.0.1.
On host machine, update the hosts file with real IP of your master server and not with loopback. 
Since, when you inside container, the host loopback and container loopback are completely different interfaces. 
In short, update  hosts  on your master server as following (after updating the hosts file, reboot the master server):
```
172.31.136.180  console.example.com
```

**Comment by maxberndt1234** [comment]
@Dimss okay thanks, that works! :)
what is the proper way in openshift to make such a DNS entry?

**Comment by Dimss** [comment]
While your OpenShift installation, you can set 
`openshift_master_cluster_hostname` and/or `openshift_master_cluster_public_hostname`
those hostnames have to be appropriate resolvable by your internal and/or external DNS. 
more details here: [https://docs.openshift.com/container-platform/3.11/install/configuring_inventory_file.html](https://docs.openshift.com/container-platform/3.11/install/configuring_inventory_file.html)

**Comment by maxberndt1234** [comment]
thanks @Dimss I will figure that out.

**Comment by maxberndt1234** [comment]
Hey @Dimss, I got one more question.

actually `openshift_master_cluster_hostname` and `openshift_master_cluster_public_hostname` are configured already (but **differ**):

```
openshift_master_cluster_hostname = cluster.example.com
openshift_master_cluster_public_hostname = console.example.com
```

The `{grafana|prometheus}-proxy` container is able to resolve `cluster.example.com` correctly to a local master ip. Unfortunately, as you can see in my first post, the `{grafana|prometheus}-proxy` is trying to make a `Post to https://console.example.com/oauth/token: EOF`. It fails to do so because it won't be able to resolve the `openshift_master_cluster_public_hostname`.

A workaround would be to provision each node with a /etc/hosts that points `openshift_master_cluster_public_hostname` to the local ips.

Is there a cleaner way? E.g., shouldn't the `{grafana|prometheus}-proxy` try to access the console via a local route? Or is obligatory to have `openshift_master_cluster_hostname` equal `openshift_master_cluster_public_hostname` when using to proxy?

**Comment by iammohan83** [comment]
Thanks. It works for me in Openshift V 3.11
