### ISSUE TITLE
Getting SIGSEGV when deploying on OpenShift

### ISSUE THREAD

**Issue by InfoSec812** [openshift/oauth-proxy#108]
I have followed the instructions on the README.md, but the proxy is crashing on me.

```
2019/03/25 13:56:51 provider.go:106: Defaulting client-id to system:serviceaccount:deven-test:proxy
2019/03/25 13:56:51 provider.go:111: Defaulting client-secret to service account token /var/run/secrets/kubernetes.io/serviceaccount/token
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x11bdedb]

goroutine 1 [running]:
main.(*Options).Validate(0xc420311180, 0x1caeae0, 0xc420362000, 0x9, 0xc420347c01)
	/go/src/github.com/openshift/oauth-proxy/options.go:208 +0x46b
main.main()
	/go/src/github.com/openshift/oauth-proxy/main.go:136 +0x1915
```

I double-checked the service account and annotation match the route for my application, I tried giving the service account various role-bindings, etc... Any help would be GREATLY appreciated!!

**Comment by InfoSec812** [comment]
Also, that error seems to indicate that the redirect URL is not being properly retrieved from the service account annotation.

**Comment by InfoSec812** [comment]
Also, the Template I am using can be found here: https://github.com/InfoSec812/ocp-oauth-sidecar-example/blob/master/.openshift/templates/deploymentconfig.yml

Deploying this on OpenShift Container Platform 3.11

**Comment by InfoSec812** [comment]
The deployed Service Account looks like:

```
apiVersion: v1
imagePullSecrets:
  - name: proxy-dockercfg-cq542
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"oauth-test"}}
  creationTimestamp: '2019-03-25T13:36:58Z'
  labels:
    template: oauth-sidecar-template
  name: proxy
  namespace: deven-test
  resourceVersion: '2338432'
  selfLink: /api/v1/namespaces/deven-test/serviceaccounts/proxy
  uid: 0fea2a45-4f03-11e9-a917-fa163e0a6c91
secrets:
  - name: proxy-token-w2dkg
  - name: proxy-dockercfg-cq542
```

**Comment by enj** [comment]
It seems to be panicing on this line:

https://github.com/openshift/oauth-proxy/blob/db14cbda06c6771dae947031c3e98c3ee7bc8cb3/options.go#L208

meaning that something is off about your `upstream` URL.

**Comment by InfoSec812** [comment]
@enj Agreed, but I followed the instructions as detailed. The `upstreamURL` should be coming from the Route.

**Comment by stlaz** [comment]
https://github.com/openshift/oauth-proxy/pull/109 fixes the seg. fault but you'll still need to pass the proper upstream URL

**Comment by enj** [comment]
This is the config param that it is unhappy about:

https://github.com/InfoSec812/ocp-oauth-sidecar-example/blob/master/.openshift/templates/deploymentconfig.yml#L50

**Comment by InfoSec812** [comment]
Yep, found the issue... My OCP template was not processing correctly so the upstream URL in the route was something like `http://localhost:${{APP_PORT}}` LITERALLY... The template substitution didn't happen for some reason.

**Comment by InfoSec812** [comment]
@stlaz Thanks for patching that so quickly!!! Ill close this now!
