### ISSUE TITLE
Use oauth-proxy as OpenShift okd customized router

### ISSUE THREAD

**Issue by gianluca-sabena** [openshift/oauth-proxy#114]
Is it possible to use oauth-router as a OpenShift okd customised router https://docs.openshift.com/container-platform/3.11/install_config/router/customized_haproxy_router.html#install-config-router-customized-haproxy

Use case:
- one openshift okd cluster
- use oauth-router as a OpenShift okd customised router 
- user can deploy pod and user openshift route resources as always
- non need to have a pod sidecar for any service

Thank you

**Comment by stlaz** [comment]
No, not possible
