### ISSUE TITLE
OAuth-Proxy external access to console

### ISSUE THREAD

**Issue by AbrahamArellano** [openshift/oauth-proxy#115]
Hi,

I'm trying to configure the OAuth Proxy in a AWS server outside Openshift Dedicated. The OAuth Proxy should be the entry point for the Web Console of Openshift and all requests from the browser must go through the proxy.

Our approach is to run OAuth Proxy as a docker container using the following configuration:

``--upstream=https://api.openshift.com,file:///var/oauth/well-known/#/.well-known/,https://console.openshift.com/console \
--provider=openshift \
--cookie-secret=SECRET \
--tls-cert=/var/run/secrets/oauth-proxy.tls.crt \ (self signed)
--tls-key=/var/run/secrets/oauth-proxy.tls.key \
--client-id=openshift-web-console \
--client-secret=test \
--ssl-insecure-skip-verify=true \
--request-logging=true \
--skip-auth-regex=".*well-known.*|.*oauth\/authorize.*|.*oauth\/token.*|.*\/login.*" \``

However, we have different issues:
- Every call to the upstream causes: "http: TLS handshake error from 10.80.23.223:64388: remote error: tls: unknown certificate"
- The documentation is not clear on how to setup the client-id and client-secret for OAuth clients for this type of scenarios.
- In case of multiple upstreams, how to handle the upstream-ca value?
- There is no real examples or documentation of the configuration for a scenario of OAuthProxy outside Openshift.
- Is there any recommended approach to cover the authentication of the console?

Thanks,

**Comment by mrogers950** [comment]
This is not really a supported configuration, it's supposed to be run on an OpenShift cluster, not outside of it with docker. Either way, the console is protected by OpenShift native OAuth by default, so you should not have to try to configure an external oauth-proxy to do that.

**Comment by wgordon17** [comment]
@mrogers950 I understand that while this isn't supported...this is a specific use case where @AbrahamArellano is needs to run the web console at a specific URL, but OpenShift Dedicated doesn't currently support that. So they're trying to use the `oauth-proxy` as a work around for this specific restriction. Is there _any way_ it could be possible to run `oauth-proxy` externally to the cluster?

**Comment by mrogers950** [comment]
@wgordon17 @AbrahamArellano the main issue is that the proxy is hard-wired to use the service account token to perform token reviews. The SA token is automatically provided to /var/run/secrets/kubernetes.io/serviceaccount/token on an in-cluster container and the proxy assumes this. You won't have the SA token available outside of the cluster unless you export it and provide it with -client-secret.  But the problem with this approach is that if the token is replaced your proxy would stop working unless you manually update it.
.

**Comment by wgordon17** [comment]
@mrogers950 Thank you for that clarification. I would _suspect_ that rotating service account token occasionally would be preferable over not having this work at all, but I'll have to let @AbrahamArellano speak to that since he's the one working with the customer.

Are you able to provide any guidance here, provided that the customer would be OK with exporting the service account token?

**Comment by mrogers950** [comment]
No guarantees (and I truly dislike the idea of exporting a SA token outside of the cluster. It's very dangerous to do so), but try setting `-client-id` to `system:serviceaccount:<namespace>:<sa>` to a valid SA and `-client-secret` to its SA token. To answer the other questions about the original config, `-upstream-ca` and `-openshift-ca` needs to be set to the OpenShift CA. Also, options that take more than one value are specified multiple times with one value each. You will also not want to use `--ssl-insecure-skip-verify=true`

**Comment by wgordon17** [comment]
@mrogers950 I'm just testing this on my own now with

```
./oauth-proxy \
    --upstream=https://api.bu-demo.openshift.com \
    --upstream=file:///var/oauth/well-known/#/.well-known/ \
    --upstream=https://console.bu-demo.openshift.com/console \
    --provider=openshift \
    --cookie-secret=SECRET \
    --tls-cert=certs/tls.crt \
    --tls-key=certs/tls.key \
    --client-id=system:serviceaccount:wgordon:oauth \
    --client-secret=XXX \
    --request-logging=true \
    --skip-auth-regex=".*well-known.*|.*oauth\/authorize.*|.*oauth\/token.*|.*\/login.*" \
    --upstream-ca=certs/ca.crt \
    --openshift-ca=certs/ca.crt
```

And I'm seeing `Get https://kubernetes.default.svc/.well-known/oauth-authorization-server: dial tcp: lookup kubernetes.default.svc: no such host`. Is there another config that I need to set for this?

**Comment by mrogers950** [comment]
@wgordon17 set KUBERNETES_SERVICE_HOST to change that.

**Comment by wgordon17** [comment]
Ok, now running with

```
env KUBERNETES_SERVICE_HOST=api.bu-demo.openshift.com ./oauth-proxy \                                                                                              9s  Fri Apr 12 13:18:08 2019
    --upstream=https://api.bu-demo.openshift.com \
    --upstream=file:///var/oauth/well-known/#/.well-known/ \
    --upstream=https://console.bu-demo.openshift.com/console \
    --provider=openshift \
    --cookie-secret=SECRET \
    --tls-cert=certs/tls.crt \
    --tls-key=certs/tls.key \
    --client-id=system:serviceaccount:wgordon:oauth \
    --client-secret=eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ3Z29yZG9uIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6Im9hdXRoLXRva2VuLWptemc2Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6Im9hdXRoIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiN2JiZjRkMTEtNWQzYy0xMWU5LTgxZDctMGVmOWFjY2VhYmQ0Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Ondnb3Jkb246b2F1dGgifQ.qQ7b2Ps4rgxCDEHe7qbLWnpZ3eBK5PBWs3U8MZx65j-2qnzJEWYttMCAV7z_imbiKCbLhdi40rQxda2UmyFtInb_1SggysbPpXxPmAm9Xn5XPW8_OkKePZSjTDDOjiIAAb-6_OhZqd39fmF_vBI8zGe4i6lKj1qKrz_J0n60PkAKl48uN1TCrwqk6SNF1iPVyrQE9Fd5-ANAb40-thHXLkKDBRA5JvzUBmG4lFrWHXEeQouFgVmiTdcEYpH2Euhf6lVr_xHnUkcV2KA8QdfNjrhzE9mgraZd9UiwQ-4_1qdRUAiaTANetQFBtdoiyrmXCVgFMxKezjIx3uqZTZaYOA \
    --request-logging=true \
    --skip-auth-regex=".*well-known.*|.*oauth\/authorize.*|.*oauth\/token.*|.*\/login.*" \
    --upstream-ca=certs/ca.crt \
    --openshift-ca=certs/ca.crt
```

I'm seeing `Get https://api.bu-demo.openshift.com/.well-known/oauth-authorization-server: x509: certificate signed by unknown authority`

The `certs/tls.crt` and `certs/tls.key` were self-signed certs (could that be the issue?). And `certs/ca.crt` was taken from a pod running on the cluster at `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`

**Comment by mrogers950** [comment]
@wgordon17 
```
$ openssl s_client -connect api.bu-demo.openshift.com:443
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = *.bu-demo.openshift.com
verify return:1
---
Certificate chain
 0 s:CN = *.bu-demo.openshift.com
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
 1 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
```
Dedicated uses LetsEncrypt wildcard for the domain so you'll need to set ca.crt to the LE public trust bundle.

**Comment by wgordon17** [comment]
@mrogers950 This is great, thanks for your help! So, adding the LE intermediate certificate, and adding a redirect URI annotation to the serviceaccount allowed me to get far enough to grant the oauth permissions, but when it redirected back I received a browser error `502: localhost is unable to handle this request`. Is it safe to assume that I should set `--redirect-url` to an application that can properly handle the returned token?

**Comment by mrogers950** [comment]
@wgordon17 I'm not exactly sure what would lead to that browser error (a mismatch in redirects?) but the redirect URL would most likely need to be pointed to the forward-facing url of this standalone running proxy. It would also need to match the redirect on the SA
