### ISSUE TITLE
OAuth on kubernetes

### ISSUE THREAD

**Issue by laurafitzgerald** [openshift/oauth-proxy#119]
Is it possible to use oauth-proxy on kubernetes. It's mentioned in the README.

However, according to OpenShift docs: 
// RedirectReference specifies the target in the current namespace that resolves into redirect URIs.  Only the 'Route' kind is currently allowed. Route is not an a Kubernetes resource. Is there any plans to make it work with Ingress?

**Comment by enj** [comment]
OAuth proxy requires the OpenShift integrated OAuth server which requires the OpenShift API server.  Thus it will not work on vanilla Kubernetes.

**Comment by laurafitzgerald** [comment]
Should the reference to it working on Kubernetes be removed from the README?

**Comment by enj** [comment]
Sorry I did a poor job of explaining.  The auth delegation bits will work fine on vanilla Kubernetes.  The OAuth bits that you are referencing are OpenShift specific.
