### ISSUE TITLE
Prompted for login even with a valid cookie

### ISSUE THREAD

**Issue by mikemowgli** [openshift/oauth-proxy#122]
Here's the expected scenario:
1) I log inside my openshift cluster, and provide my credentials in the login page
2) I then browse to my application faced by the oauth-proxy
3) I have to give my consent and I'm directly forwarded to my app

Here's the actual scenario:
1) & 2) are the same
3) I have to give my consent, **and I'm redirected to the login page again**, even though I have a valid openshift cookie

I played with the '-approval-prompt' flag, setting it alternatively to 'force', 'consent', and 'none'.

How can I make it that the oauth proxy would ask for my consent, but notice I have a valid token and redirect to my app with having to provide credentials again?

**Comment by enj** [comment]
This is the expected behavior.  Each login with OpenShift is only valid for a single OAuth flow.  Your cluster must be configured with an IDP that maintains a session (i.e. GitHub) if you do not wish to be re-promoted on each login.
