### ISSUE TITLE
Where did openshift/oauth-proxy:v1.1.0 build from

### ISSUE THREAD

**Issue by crazytaxii** [openshift/oauth-proxy#124]
The docker image openshift/oauth-proxy:v1.1.0 (https://hub.docker.com/r/openshift/oauth-proxy) was built a year ago, I cloned this repository and tried to build the same version but failed. It looks like no branch related to  image or binary in openshift/oauth-proxy:v1.1.0.

**Comment by sveneh** [comment]
/remove-lifecycle rotten

Still the same question: Where is the official container image from the latest code being hosted? The image on docker hub is 4 years old, so this cannot be the latest version.
