### ISSUE TITLE
Missing switch to configure custom CA to use against the server being proxied

### ISSUE THREAD

**Issue by jcantrill** [openshift/oauth-proxy#13]
Trying to front the prometheus endpoint for Elasticsearch in the Openshift logging stack.  The proxy always generates 502 errors.  @simo5 suggested it is because we are unable to provide a custom CA which is how the logging stack secures communication to its components

**Comment by smarterclayton** [comment]
Original use case was running as local proxy talking to HTTP.  I'm fine with an upstream CA being added (I don't know that oauth-proxy had it either).

Note that where possible running the proxy as a sidecar is expected, rather than creating a new proxy layer.

**Comment by smarterclayton** [comment]
The proxy expects to get service serving TLS certs injected (not with code, but with assumptions of setup).

**Comment by simo5** [comment]
In what way a sidecar is not a proxy ?
The use case this was requested for is oauth-proxy running in the same pod as the target where the target server uses only HTTPS and has own CA + certs, and does not allow clear text connections.

**Comment by simo5** [comment]
Also side question, can we stop calling th target "upstream", it is really confusing, "target" seem pretty clear.
