### ISSUE TITLE
Pass OpenShift roles in header

### ISSUE THREAD

**Issue by dastrobu** [openshift/oauth-proxy#132]
I want to secure an application behind the oath-proxy. Securing one end-point based on a single role can easily be done. The application itself, however should be able to check the role of the user and allow usage of some endpoints and methods based on the actual roles of the user. 

To that end, it would help if the actual roles of the user could be passed as an additional header.

**Comment by stlaz** [comment]
The oauth-proxy has no knowledge of which roles the user is bound to and therefore it won't be able to pass them on. It does not even know about the user's groups.

**Comment by dastrobu** [comment]
ok I see, took a look into this. 
The `SubjectAccessReview` does not provide any roles. Certainly the OAuthProxy could query the `RoleBinding`s to pass that on, but I agree that this might be out of scope and the upstream app (or another proxy in the middle) could do that.
