### ISSUE TITLE
Setting an Openshift CA should not include System Roots certs

### ISSUE THREAD

**Issue by simo5** [openshift/oauth-proxy#14]
The current SetCA function unconditionally tries to fetch System Roots, this should not be done, when people indicate a CA they normally intend to allow only certs from said CA and nothing else.

**Comment by smarterclayton** [comment]
SGTM

**Comment by smarterclayton** [comment]
I may have hit this on some edge case, but I doubt it.

**Comment by simo5** [comment]
Note that this is a multivalue string array, so if you really want to include root CAs you can explicitly list the bundle pem on the command line.

Just making it clear that by changing this we are not going to regress in functionality in any way and we are giving the admin full control of what CA certs to trust.
