### ISSUE TITLE
How to implement logout after inactivity period?

### ISSUE THREAD

**Issue by Megan-Wright** [openshift/oauth-proxy#153]
I'm trying to use `cookie-expire` to set a timeout period for logging users out of a system, but I only want this to trigger when the user has been inactive for this amount of time (as opposed to timing out even when the user is active). I thought that using `cookie-refresh`, set to a reasonably small period of time, would refresh the timeout period if the user had been active in that period of time, but this seems to have the same effect as `cookie-expire` of timing the user out after the period of time that I set.... is there another way of achieving this?

**Comment by stlaz** [comment]
You don't, unless you add code to handle inactivity timeout in sessions.
