### ISSUE TITLE
Should Cookies be deleted when you log out 

### ISSUE THREAD

**Issue by CarolynMabbott** [openshift/oauth-proxy#154]
I have an application using oauth-proxy and when I log out I expect to have to re-enter my password when i try to log back in 
Currently I can just press log in with openshift again after logging out and I dont need to re-enter my password and it just logs me in
Is this expected behaviour? 
Or am i missing some configuration settings to make sure after a log out the password needs to be entered again

**Comment by stlaz** [comment]
It depends on the IdP used, if it's an SSO and caches your login, it may be that no password is required on successive logins.

https://github.com/openshift/oauth-proxy/pull/176 may help in this case.
