### ISSUE TITLE
Is there functionality to limit the amount of times a user can try and log in?

### ISSUE THREAD

**Issue by CarolynMabbott** [openshift/oauth-proxy#155]
I cannot find any documentation around this
Is there a setting to limit the amount of tried a user has to log in before it locks the user out / anything similar if there is too many failed log in attempts?

**Comment by CarolynMabbott** [comment]
@stlaz  I was told you may be possibly be able to tell me if this functionality is in oauth-proxy or if it is planned to be added in the future?

**Comment by CarolynMabbott** [comment]
@stlaz Hi again, I am from IBM and would very much like to talk to you about this issue we raised and a few similar issues 
It would be of great help if you could contact me as we are trying to fix some medium-severity security issues on Tekton and we would like to fix these using oauth-proxy 
Feel free to contact me on Slack (Am in Tekton Slack) or Github

**Comment by stlaz** [comment]
@CarolynMabbott OpenShift itself does not implement account lockouts, that should be done in the IdPs
