### ISSUE TITLE
How do you stop a browser from caching your credentials?

### ISSUE THREAD

**Issue by Megan-Wright** [openshift/oauth-proxy#156]
When I use `cookie-expire` to cause a session timeout, and am redirected to the Openshift login page, all I am required to to do log back in is press the login button. This seems like odd behaviour, as I would expect to need to re-enter my openshift credentials into the browser in order to log back in.... how would I stop a browser from caching these pre-entered credentials in order to force a user to re-enter them every time they want to log in? @stlaz I've been advised you might be able to help with this?

**Comment by stlaz** [comment]
@Megan-Wright you need to check the sessions at your IdP. You can now also configure --logout-url (https://github.com/openshift/oauth-proxy/pull/176) to log you out from your SSO as well so that whenever you try to re-login, you need to insert all your credentials again.
