### ISSUE TITLE
504 Gateway timeout

### ISSUE THREAD

**Issue by srazasuper** [openshift/oauth-proxy#166]
Hey Team Im using this proxy and it looks very promising. 
The problem Im facing is 504 gateway timeout when I try to run a long report. If i try the report url directly it works but than I lose the Openshift Authentication.
Is there anyway I can define timeout to be longer for upstream.

**Comment by srazasuper** [comment]
Dev team.
Iam stuck here. We really like the project but we need to set atleast 20 Minutes for long HTTP backend/upsteam requests

**Comment by bharaththiruveedula** [comment]
@srazasuper Currently facing same issue, did you get any workaround?
