### ISSUE TITLE
Can oauth-proxy run as non root

### ISSUE THREAD

**Issue by clyang82** [openshift/oauth-proxy#181]
I saw the current oauth-proxy process is running as root. Any impacts on `runasnonroot`? Do we have plan to support `runasnonroot`?

**Comment by clyang82** [comment]
@sttts @stlaz @deads2k could you provide your comments or suggestions here? Thanks.

**Comment by stlaz** [comment]
Have you had any problems running it as non-root? I can't think of a reason that would prevent that

**Comment by deads2k** [comment]
running as non-root works fine.  We use it in several places in openshift.  How you choose to run it is up to how you describe the pod, but you can see non-root invocations in  openshift like https://github.com/openshift/cluster-monitoring-operator/blob/e46a186a877af3cb07a6d4a66f143d260c2bdbe2/assets/alertmanager/alertmanager.yaml

it runs with a low SCC and random user UID

/close

**Comment by clyang82** [comment]
Thanks @deads2k @stlaz That is my fault. I should not use `443` which cannot be listened by non-root.
