### ISSUE TITLE
How to logout kubeadmin user?

### ISSUE THREAD

**Issue by bharaththiruveedula** [openshift/oauth-proxy#195]
In case of non-kubeadmin user, I am deleting oauth-proxy, so when logged out , oauth-proxy asks for credentials. But in case of kubeadmin user even after logout, and then clicking on login button directly redirects to my homepage without asking for credentials.

I am using **openshift** provider

**Comment by stlaz** [comment]
The cluster's oauth-server keeps the session opened for the kubeadmin user, as would any other 3rd party SSO system hold it for their users.

The easiest way to destroy the kubeadmin's session is to go to the `/oauth/token/request` page of the oauth-server, click "Display token" and then click "Logout".
HTH
