### ISSUE TITLE
Sign-in message problems

### ISSUE THREAD

**Issue by mffiedler** [openshift/oauth-proxy#20]
Hitting the prometheus route in OCP 3.7.0-0.143.0 results in a prompt:

"Sign in with a Account"

1) grammatically, it should be "an account"
2) Looking at tempates.go, it appears there should be a ProviderName insert in the message.   Maybe "Sign  in with an OpenShift account"?

**Comment by simo5** [comment]
@mffiedler do we need this fixed in 3.7 ?

**Comment by mffiedler** [comment]
@simo5 I think we should if there is an opportunity.   Certainly not a blocker, but gives a bit of a bad impression.

**Comment by mffiedler** [comment]
Verified this is fixed in this image:  docker.io/openshift/oauth-proxy                                  v1.0.0              e341071d3540
