### ISSUE TITLE
Support for GRPC

### ISSUE THREAD

**Issue by jotak** [openshift/oauth-proxy#205]
Hi,

Is the proxy supposed to support GRPC? And if not, is it planned / doable?

To add a little bit of context, I'm trying to use grpc between some ossm (service mesh) components, but at this point I wasn't able to have it work with oauth-proxy in the middle.

My oauth-proxy logs seem to indicate the authorization succeeds:
```
2021/02/10 13:30:42 oauthproxy.go:843: authenticated "internal" via basic auth
```

But then, the connection fails, client-side showing: 
```
rpc error: code = Unavailable desc = connection closed
```

Here's the proxy config:
```
          args:
            - '--cookie-secret=...'
            - '--display-htpasswd-form=false'
            - '--htpasswd-file=/etc/proxy/htpasswd/auth'
            - '--https-address=:8443'
            - >-
              --openshift-sar={"namespace": "istio-system", "resource": "pods",
              "verb": "get"}
            - '--openshift-service-account=jaeger-ui-proxy'
            - '--provider=openshift'
            - '--tls-cert=/etc/tls/private/tls.crt'
            - '--tls-key=/etc/tls/private/tls.key'
            - '--upstream=http://localhost:16686'
```

If I bypass the proxy to hit directly the jaeger service on port 16686, the connection succeeds.

**Comment by stlaz** [comment]
OAuth2 flows over a protocol other than HTTP are not very common (or at least I haven't seen a project that would do such a thing, yet the protocol allows it so it is possible).

You seem to have used HTTP basic-auth, so you've practically worked around all the possible merit this proxy provides, so I am not sure you're using the right tool for the job.

That being said, we do not plan on expanding the protocols that are supported by the proxy.

**Comment by jotak** [comment]
Thanks for your response,
Just to understand, is it the reverse-proxy thing (forwarding traffic to upstream) that is too unusual as grpc, or the authorization flow to the oauth server? I'm not asking the oauth flow itself to be over grpc (and actually this part seems to work fine if I believe the logs)

**Comment by stlaz** [comment]
You bypassed the authorization flow. So it is both that and the reverse-proxy part.
