### ISSUE TITLE
Is there any way to access the username of the loged in user?

### ISSUE THREAD

**Issue by vamseekrishna25** [openshift/oauth-proxy#208]
as oauth proxy is accessing user info etc while logging in is there a way to accesses username of the user logged through oauth proxy  in the application

**Comment by omhingmire** [comment]
You can call the following API with the token you have:

https://<api-server>:<port>/apis/user.openshift.io/v1/users/~

you will get the user info like name/groups etc.

**Comment by vamseekrishna25** [comment]
how do we get the token is it present in the cookie of oauth proxy ?

**Comment by zohiba** [comment]
did anyone figure out how to get the token?
