### ISSUE TITLE
Need the username/info from application

### ISSUE THREAD

**Issue by zohiba** [openshift/oauth-proxy#213]
Once the user is validated using the oauth proxy, is there a way to pass in that user info to the application?

**Comment by vamseekrishna25** [comment]
there is a way to access the username of the logged-in user through the cookie created by OAuth proxy by disabling HTTPS only and secure to false. you can access cookie value through your frontend javascript with the help of libraries like js-cookie etc .the cookie value is base64 encoded so you need to decode it and you can get the username

**Comment by zohiba** [comment]
are you sure it is disabling HTTPS only ? I don't see any such option. I thought these are the two you were talking about 
`"--cookie-secure=false",
"--cookie-httponly=false",`

**Comment by vamseekrishna25** [comment]
yes  "--cookie-secure=false", "--cookie-httponly=false" are the options to disable  HTTPS only and secure. if you don't want to disable httpsonly for security reasons you can pass the cookie with your request to the server and decode in the server

**Comment by zohiba** [comment]
can you explain a little more on "how to pass the cookie with your request to the server"?

**Comment by zohiba** [comment]
HI @vamseekrishna25 do you know what configuration I should use to encrypt the _oauth_proxy value? I read I could use `--cookie-secret-file` or `--cookie-secret` but it is not working for me, I still see the value as base64 encoded, rather than getting encrypted with the secret I provided. Basically, I want the username to be secure and not easily decoded.
