### ISSUE TITLE
Need user authorization token for proper RBAC settings on custom backend APIs

### ISSUE THREAD

**Issue by ivandov** [openshift/oauth-proxy#221]
I believe this question is similar to the problems referenced in #107 and #111. 

I have a frontend/backend application that is interfacing directly with OCP `CustomResources` that we manage through our application. We have backend APIs that manage these CRs based on user actions.

I want to secure these APIs using the `oauth-proxy` and only allowing users with certain RBACs to be able to perform appropriate CRUD actions based on their RBAC settings for our various CRs. I also want to restrict portions of our frontend based on a user's authorizations (i.e. if they're not what we consider our "app admin persona", then they shouldn't be able to use certain UIs). 

Since we have a slew of APIs, I would need to craft some pretty dynamic `SubjectAccessReview` requests in order to properly secure my API. For example, I want to have a frontend UI that can only be displayed if a user has RBAC permissions to `get` on a `CustomInstance` (example CR `kind`) with `resourceName: foo`. 

As far as I can tell, the `SAR` that I'd have to write in the `oauth-proxy` config wouldn't be able to easily set the dynamic values for the `resourceName` for various users and various APIs, and therefore I wouldn't be able to craft unique SARs for individual users. 

Wouldn't I need the authenticated user's Bearer Token on our backend? Then I'd be able to call the `apis/authorization.openshift.io/v1/subjectaccessreviews` API directly with the user's token and identify if they have the proper permissions needed for our a specific API. 

Am I missing something? Is there some other way that this can be done? Only other solution I'm considering is making our backend act as a full oauth client, but, that seems like redundant implementations when the `oauth-proxy` already handles all of this for me.

**Comment by ivandov** [comment]
Any update here? Or suggestion on a different direction to take?

**Comment by tuananh** [comment]
I'm interested in this as well
