### ISSUE TITLE
refresh OpenShift token

### ISSUE THREAD

**Issue by sparkoo** [openshift/oauth-proxy#225]
Is there a way how to refresh OpenShift token? Now when OpenShift expires, AFAIU oauth-proxy is still using the old token, which is useless. Only improvement I've achieved is to set the oauth-proxy cookie lifetime to match the openshift token lifetime. This is not ideal as well. In both cases, if OpenShift token expires in the middle of long procedure doing multiple OpenShift API requests, it simply start failing the requests in the middle. It would be better if oauth-proxy could refresh the token in the background. Alternatively, I think it would be an UX improvement when the token expires, invalidate the cookie and redirect to login page. WDYT ?

**Comment by jianzhangbjz** [comment]
Hi, I reopen this issue since I met the same problem about the token refresh. Please feel free to close it if we have already addressed this issue, thanks!

**Comment by jianzhangbjz** [comment]
> Only improvement I've achieved is to set the oauth-proxy cookie lifetime to match the openshift token lifetime.

@sparkoo Hi, how long is the OpenShift token lifetime? Or where can I get it? Thanks!

**Comment by sparkoo** [comment]
> > Only improvement I've achieved is to set the oauth-proxy cookie lifetime to match the openshift token lifetime.
> 
> @sparkoo Hi, how long is the OpenShift token lifetime? Or where can I get it? Thanks!

@jianzhangbjz default openshift token lifetime is 24hrs. You can see and change it with `oc edit oauth cluster` (https://docs.openshift.com/container-platform/4.10/authentication/configuring-internal-oauth.html#oauth-configuring-internal-oauth_configuring-internal-oauth).

I think it's not possible to refresh the access token, or at least I couldn't find any way how to do it. Only "solution" I've found is to match (or set lower) cookie lifetime with token lifetime.

**Comment by jianzhangbjz** [comment]
@sparkoo Yeah..., thanks very much!

**Comment by stlaz** [comment]
The oauth-proxy does not in fact store the token even though there appears to be _some_ code wiring that suggests otherwise. OpenShift does not mint refresh tokens. Hence this cannot be done.
