### ISSUE TITLE
The page isn’t redirecting properly

### ISSUE THREAD

**Issue by clyang82** [openshift/oauth-proxy#232]
I am using oauth-proxy in front of my service. I want to leverage the oauth-proxy capability to do authentication. Here is my configuration for oauth-proxy

```
    - --provider=openshift
    - --upstream=https://xxx.svc:8443
    - --upstream-ca=/etc/tls/ca/service-ca.crt
    - --https-address=:9443
    - --client-id=multicloudingress
    - --client-secret=xxxxxx
    - --pass-user-bearer-token=true
    - --pass-access-token=true
    - --scope=user:full
    - '-openshift-delegate-urls={"/": {"resource": "projects", "verb": "list"}}'
    - --skip-provider-button=true
    - --cookie-secure=true
    - --cookie-expire=12h0m0s
    - --cookie-refresh=8h0m0s
    - --tls-cert=/etc/tls/private/tls.crt
    - --tls-key=/etc/tls/private/tls.key
    - --cookie-secret=xxxx
    - --openshift-ca=/etc/pki/tls/cert.pem
    - --openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
```
I enabled auto-refresh for my page. I found that if the cookie is expired. sometimes, I can meet this below problem.
first:
<img width="585" alt="image" src="https://user-images.githubusercontent.com/7711311/140528019-6ff8022a-1baa-4ef2-a3b7-3764420ba623.png">
click to login 
<img width="548" alt="image" src="https://user-images.githubusercontent.com/7711311/140528057-41c47e1b-2cf5-4f7e-bc5f-51de593d10ff.png">
then `Log in with OpenShift`
<img width="876" alt="image" src="https://user-images.githubusercontent.com/7711311/140528133-6b730c46-7f11-4fda-a94b-0ef21e11e519.png">

I cannot go to my page. I have to close my browser and relogin. 
I am not sure if my usage is wrong or something wrong around oauth-proxy.
Appreciate for any suggestions. 
I can append more details if needed. Thanks.

**Comment by clyang82** [comment]
@stlaz could you provide your comments or suggestions here? Thanks.

**Comment by clyang82** [comment]
append why the page is not redirecting properly. it is due to dead loop
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/7711311/140899177-2f07f58e-ef3d-4536-a71f-789c7a1971d6.png">

**Comment by s-urbaniak** [comment]
Your nonce value stored in the `_oauth2_proxy_csrf` cookie, secured by the cookie secret does not match the nonce value returned from the oauth callback passed via the `state` request parameter. Make sure your oauth server respects and returns the right value.

**Comment by clyang82** [comment]
@s-urbaniak Thanks for your reply. Could you elaborate more how to make the values is returned within the callback correctly? As I understand, the `_oauth2_proxy_csrf` cookies is set via `SetCSRFCookie` method. And the callback is also set by `SetCSRFCookie` method. 
https://github.com/openshift/oauth-proxy/blob/9ea1ebc89f721d3cd929f58c7ab9ed4273d3c493/oauthproxy.go#L610:L630
Where is my configuration wrong?

**Comment by ibihim** [comment]
When the flag `--skip-provider-button` is set to `true`, you can't pass the target URI as a parameter.
You will be always redirected to the host with an authenticated session.

If you want to redirect to a relative path, you need to set `--skip-provider-button` to `false`.

**Comment by ibihim** [comment]
There is a CSRF token set. It prevents CSRF attacks. It is quite common to limit the life span of such tokens to a short period of time. This is not a bug.

**Comment by clyang82** [comment]
@ibihim Thanks for your response. We have switched to set `--skip-provider-button` to `false`.
