### ISSUE TITLE
can we encrypt username stored in oauth_proxy cookie ?

### ISSUE THREAD

**Issue by zohiba** [openshift/oauth-proxy#250]
Currently the _oauth_proxy cookie stores username information that is base64 encoded which is easy to decrypt. This is a security hole, can we encrypt it somewhere before it is assigned as the cookie value? How to encrypt the username before it is assigned as the cookie value?

Edit: I have tried using the --cookie-secret flag like `--cookie-secret=8_3IDOJAfTYz3plnjmD5pAbLr9BiJv81L-fuMoEynro=` but the cookie is not getting encrypted, it is still in base64 form. I have the following version that supports the flag but it is still not working. 
```sh-4.4$ oauth-proxy --version
oauth2_proxy was built with go1.19.4
```

**Comment by amandalal** [comment]
@stlaz @jianzhangbjz Do either of you know if this project is still being maintained? We are using this product and this is considered a security flaw.

**Comment by amandalal** [comment]
@openshift-bot /reopen

**Comment by amandalal** [comment]
@stlaz @jianzhangbjz Do either of you know if this project is still being maintained? We are using this product and this is considered a security flaw.

**Comment by zohiba** [comment]
@openshift-bot /reopen

**Comment by amandalal** [comment]
@stlaz @jianzhangbjz Do either of you know if this project is still being maintained? We are using this product and this is considered a security flaw.
