### ISSUE TITLE
404 Not Found for oauth/start

### ISSUE THREAD

**Issue by dkwon17** [openshift/oauth-proxy#264]
When entering the auth flow, after clicking "Log in with OpenShift", there is a `404 page not found` error:

<details>
<summary>Video & screenshot & config:</summary>

[ouath_start.webm](https://github.com/openshift/oauth-proxy/assets/83611742/ccc49fcb-73a8-435a-a447-33c8d590859d)

![image](https://github.com/openshift/oauth-proxy/assets/83611742/e3990b2f-b43a-47ea-a2b6-a0a6a770848c)

![image](https://github.com/openshift/oauth-proxy/assets/83611742/a1969cca-9c39-4df7-879a-78e7bd5a50e1)

</details>

<details>
<summary>What I expected to see</summary>

<img width="1437" alt="image" src="https://github.com/openshift/oauth-proxy/assets/83611742/949d99b8-2533-4f3a-92d4-06d91a21686f">

</details>

This issue happens on some occasions, not always. Refreshing the page fixes the issue, but I'm confused why it is happening in the first place. We are using `release-4.12`.

Any ideas?

**Comment by stlaz** [comment]
the main page appears to be at the `/dashboard` suffix, the oauth-proxy redirects you to `/start`.

Try running it on root.
