### ISSUE TITLE
Where are the images of this project currently published?

### ISSUE THREAD

**Issue by cg1410** [openshift/oauth-proxy#273]
Hello!
I am currently using 3.11 version of docker image from that repository in my openshift cluster.
I would like to update the proxy to the latest version (which i believe supports openshift 4), but i cannot see, where do You currently publish the docker images.
I have found some image here: https://quay.io/repository/openshift/origin-oauth-proxy but honestly, i have no idea if that is what i am looking for. There is no single word in that repository where should i look for the right image.

Please fix the documentation or explain if those images are still public available.

Best regards

**Comment by Victoremepunto** [comment]
@cg1410 I think you're right, I believe that is the actual repository for the oauth proxy, considering it is part of the openshift/release project 

I've opened #277 to help close this issue.
