### ISSUE TITLE
ssl-insecure-skip-verify is not taken into account

### ISSUE THREAD

**Issue by akram** [openshift/oauth-proxy#36]
Hi,

ssl-insecure-skip-verify does not seem to taken into account:
```
2017/12/01 11:36:19 oauthproxy.go:582: error redeeming code (client:10.129.0.1:45870): Post https://api.ocp.rhlab.me.com/oauth/token: x509: certificate signed by unknown authority
```
I added the 
ssl-insecure-skip-verify and I still have the issue
 oauthproxy.go:+L582 does not have the check

**Comment by simo5** [comment]
This is a good thing! right ? :-)

**Comment by simo5** [comment]
more seriously, you should never need to skip TLS verification against openshift, because we always have the openshift CA available. In what case this is not true for you ?

**Comment by pradeeppandeyy** [comment]
Cookie "_oauth_proxy" not present

2018/01/24 01:55:04 provider.go:265: Delegation of authentication and authorization to OpenShift is enabled for bearer tokens and client certificates.
--
  | 2018/01/24 01:55:04 oauthproxy.go:161: mapping path "/" => upstream "http://localhost:9093"
  | 2018/01/24 01:55:04 oauthproxy.go:184: compiled skip-auth-regex => "^/metrics"
  | 2018/01/24 01:55:04 oauthproxy.go:190: OAuthProxy configured for  Client ID: system:serviceaccount:prometheus:prometheus
  | 2018/01/24 01:55:04 oauthproxy.go:200: Cookie settings: name:_oauth_proxy secure(https):true httponly:true expiry:168h0m0s domain:<default> refresh:disabled
  | 2018/01/24 01:55:04 http.go:96: HTTPS: listening on [::]:10443
  | 2018/01/24 01:55:12 oauthproxy.go:657: 10.129.0.1:51132 Cookie "_oauth_proxy" not present
  | 2018/01/24 01:55:12 provider.go:345: authorizer reason: User "system:anonymous" cannot get namespaces in project "prometheus"
  | 2018/01/24 01:55:12 oauthproxy.go:657: 10.129.0.1:51132 Cookie "_oauth_proxy" not present
  | 2018/01/24 01:55:12 provider.go:345: authorizer reason: User "system:anonymous" cannot get namespaces in project "prometheus"

**Comment by pradeeppandeyy** [comment]
This was the configuration issue for me.
