### ISSUE TITLE
Misconfiguration of /ping endpoint ?

### ISSUE THREAD

**Issue by paoloantinori** [openshift/oauth-proxy#39]
Hi, I'm trying to use `/ping` endpoint in a readiness probe in k8s but I always get a 400 error, notifying me of missing params related to authentication
I actually get the same if I try to spawn a bash instance in the container and check with curl.

Surprisingly `/robots.txt` retrurns correctly a 200.

Any chance the default config is not correct and `/ping`? or anyhow, does it make sense that `/ping` and `/robots.txt` are configured differently?

**Comment by mrogers950** [comment]
@paoloantinori the current README is wrong about this, the ping endpoint is at {proxy-prefix}/healthz (default /oauth2/healthz).

**Comment by paoloantinori** [comment]
Hi @mrogers950 I still cannot access it:

<details>
  <summary>Click to expand</summary>
<pre><code>
sh-4.2$ curl -vvv https://localhost:8443/robots.txt -k 
* About to connect() to localhost port 8443 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 8443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
* 	subject: CN=syndesis-oauthproxy.myproject.svc
* 	start date: Jan 08 11:10:27 2018 GMT
* 	expire date: Jan 08 11:10:28 2020 GMT
* 	common name: syndesis-oauthproxy.myproject.svc
* 	issuer: CN=openshift-service-serving-signer@1515407869
> GET /robots.txt HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8443
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Mon, 08 Jan 2018 13:45:23 GMT
< Content-Length: 25
< Content-Type: text/plain; charset=utf-8
< 
User-agent: *
* Connection #0 to host localhost left intact
Disallow: 


# vs.


sh-4.2$ curl -vvv https://localhost:8443/healthz -k 
* About to connect() to localhost port 8443 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 8443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
* 	subject: CN=syndesis-oauthproxy.myproject.svc
* 	start date: Jan 08 11:10:27 2018 GMT
* 	expire date: Jan 08 11:10:28 2020 GMT
* 	common name: syndesis-oauthproxy.myproject.svc
* 	issuer: CN=openshift-service-serving-signer@1515407869
> GET /healthz HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8443
> Accept: */*
> 
< HTTP/1.1 302 Found
< Location: https://192.168.42.33:8443/oauth/authorize?approval_prompt=force&client_id=system%3Aserviceaccount%3Amyproject%3Asyndesis-oauth-client&redirect_uri=https%3A%2F%2Flocalhost%3A8443%2Foauth%2Fcallback&response_type=code&scope=user%3Ainfo+user%3Acheck-access&state=2842153b2731cac74d3d302120922f44%3A%2Fhealthz
< Set-Cookie: _oauth_proxy_csrf=2842153b2731cac74d3d302120922f44; Path=/; Domain=localhost; Expires=Mon, 15 Jan 2018 13:46:10 GMT; HttpOnly; Secure
< Date: Mon, 08 Jan 2018 13:46:10 GMT
< Content-Length: 349
< Content-Type: text/html; charset=utf-8
< 
<a href="https://192.168.42.33:8443/oauth/authorize?approval_prompt=force&amp;client_id=system%3Aserviceaccount%3Amyproject%3Asyndesis-oauth-client&amp;redirect_uri=https%3A%2F%2Flocalhost%3A8443%2Foauth%2Fcallback&amp;response_type=code&amp;scope=user%3Ainfo+user%3Acheck-access&amp;state=2842153b2731cac74d3d302120922f44%3A%2Fhealthz">Found</a>.

* Connection #0 to host localhost left intact



# or

curl -vvv https://localhost:8443/oauth2/healthz -k 
* About to connect() to localhost port 8443 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 8443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
* 	subject: CN=syndesis-oauthproxy.myproject.svc
* 	start date: Jan 08 11:10:27 2018 GMT
* 	expire date: Jan 08 11:10:28 2020 GMT
* 	common name: syndesis-oauthproxy.myproject.svc
* 	issuer: CN=openshift-service-serving-signer@1515407869
> GET /oauth2/healthz HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8443
> Accept: */*
> 
< HTTP/1.1 302 Found
< Location: https://192.168.42.33:8443/oauth/authorize?approval_prompt=force&client_id=system%3Aserviceaccount%3Amyproject%3Asyndesis-oauth-client&redirect_uri=https%3A%2F%2Flocalhost%3A8443%2Foauth%2Fcallback&response_type=code&scope=user%3Ainfo+user%3Acheck-access&state=37f99bffc29afb5e3addd261b86e1a24%3A%2Foauth2%2Fhealthz
< Set-Cookie: _oauth_proxy_csrf=37f99bffc29afb5e3addd261b86e1a24; Path=/; Domain=localhost; Expires=Mon, 15 Jan 2018 13:46:57 GMT; HttpOnly; Secure
< Date: Mon, 08 Jan 2018 13:46:57 GMT
< Content-Length: 358
< Content-Type: text/html; charset=utf-8
< 
<a href="https://192.168.42.33:8443/oauth/authorize?approval_prompt=force&amp;client_id=system%3Aserviceaccount%3Amyproject%3Asyndesis-oauth-client&amp;redirect_uri=https%3A%2F%2Flocalhost%3A8443%2Foauth%2Fcallback&amp;response_type=code&amp;scope=user%3Ainfo+user%3Acheck-access&amp;state=37f99bffc29afb5e3addd261b86e1a24%3A%2Foauth2%2Fhealthz">Found</a>.

* Connection #0 to host localhost left intact


</code></pre>
</details>


Consider that what I'm after is an *unathenticated* endpoint that I can configure in kubernetes probes.

**Comment by mrogers950** [comment]
@paoloantinori I mistakenly told you the default proxy prefix is /oauth2, but it is actually /oauth. can you verify that /oauth/healthz works?

**Comment by paoloantinori** [comment]
@mrogers950  I can confirm `/oauth/healthz` works fine, thank you!
