### ISSUE TITLE
Suggestions on whitelisting paths that need oauth

### ISSUE THREAD

**Issue by kargakis** [openshift/oauth-proxy#42]
I need to do oauth for a specific path only:
```
/ (no)
/trace (yes)
/tide (no)
/plugin (no)
```

Golang does not support [negative lookaheads](https://stackoverflow.com/questions/26771592/negative-look-ahead-go-regular-expressions#26792316) and I am not sure how else to write a regexp that matches all input except a given path and then negate that in order for `-skip-auth-regex` to work.

@smarterclayton @stevekuznetsov thoughts?

**Comment by smarterclayton** [comment]
Hrm.  Good question.  We could just do a `-auth-regex` and have it be applied before `-skip`, defaulting to everything.

**Comment by stevekuznetsov** [comment]
Not possible in regex to "negate" a result without negative lookarounds.
