### ISSUE TITLE
Getting error "Cookie "_oauth_proxy" not present"

### ISSUE THREAD

**Issue by pradeeppandeyy** [openshift/oauth-proxy#52]
2018/01/24 01:55:04 provider.go:265: Delegation of authentication and authorization to OpenShift is enabled for bearer tokens and client certificates.
--
  | 2018/01/24 01:55:04 oauthproxy.go:161: mapping path "/" => upstream "http://localhost:9093"
  | 2018/01/24 01:55:04 oauthproxy.go:184: compiled skip-auth-regex => "^/metrics"
  | 2018/01/24 01:55:04 oauthproxy.go:190: OAuthProxy configured for  Client ID: system:serviceaccount:prometheus:prometheus
  | 2018/01/24 01:55:04 oauthproxy.go:200: Cookie settings: name:_oauth_proxy secure(https):true httponly:true expiry:168h0m0s domain:<default> refresh:disabled
  | 2018/01/24 01:55:04 http.go:96: HTTPS: listening on [::]:10443
  | 2018/01/24 01:55:12 oauthproxy.go:657: 10.129.0.1:51132 Cookie "_oauth_proxy" not present
  | 2018/01/24 01:55:12 provider.go:345: authorizer reason: User "system:anonymous" cannot get namespaces in project "prometheus"
  | 2018/01/24 01:55:12 oauthproxy.go:657: 10.129.0.1:51132 Cookie "_oauth_proxy" not present
  | 2018/01/24 01:55:12 provider.go:345: authorizer reason: User "system:anonymous" cannot get namespaces in project "prometheus"

**Comment by pradeeppandeyy** [comment]
resolved, it was a configuration issue.

**Comment by mofakhar** [comment]
How did you manage to fix it plz?..Can you describe the steps plz.

**Comment by pradeeppandeyy** [comment]
Create service account with below configuration,

apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"alertmanager"}}'
  name: prometheus
  namespace: prometheus


and give proper permission with below command, it will work,

oc policy add-role-to-user cluster-reader system:serviceaccount:prometheus:prometheus

**Comment by enj** [comment]
> oc policy add-role-to-user cluster-reader system:serviceaccount:prometheus:prometheus

You probably want `oc create clusterrolebinding` / `oc adm policy add-cluster-role-to-user`.  `cluster-reader` is pretty broad too, `system:auth-delegator` is likely enough.

**Comment by pradeeppandeyy** [comment]
I never tried with system:auth-delegator but I guess it should be cluster reader because it should have access to read other user information.

**Comment by enj** [comment]
> I guess it should be cluster reader because it should have access to read other user information

Giving read access cluster wide is probably not the default you want to start with unless you actually know what information you need access to.

I am unaware of the specifics of what `prometheus` does in OS, so I cannot comment on what access rights it actually needs.

**Comment by mofakhar** [comment]
Shall I replace openshift.io with my cluster fqdn?
   serviceaccounts**.openshift.io**/oauth-redirectreference.primary: 
Would you mind confirming if it's the right json call:

{
  "apiVersion": "v1"
  "kind": "ServiceAccount"
  "metadata":{
    "annotations":{
       "serviceaccounts.openshift.io/oauth-redirectreference.primary":
             '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference": "kind":"Route","name":"alertmanager"}}'
     }
    "name": "prometheus"
    "namespace": "prometheus"
  }
}

Thanks in advance for all your help

**Comment by mofakhar** [comment]
I did try to push this once the json fixed:

{
  "apiVersion": "v1",
  "kind": "ServiceAccount",
  "metadata":{
    "annotations":{
       "serviceaccounts.openshift.io/oauth-redirectreference.primary":
             {"kind":"OAuthRedirectReference","apiVersion":"v1","reference": {"kind":"Route","name":"alertmanager"}}
     },
    "name": "prometheus",
    "namespace": "prometheus"
  }
}

However, getting the following error message:
oc create -f prometheus.json
Error from server (BadRequest): error when creating "prometheus.json": ServiceAccount in version "v1" cannot be handled as a ServiceAccount: [pos 134]: json: expect char '"' but got char '{'

**Comment by enj** [comment]
Read the docs, you need to escape the reference object, ex:

`"serviceaccounts.openshift.io/oauth-redirectreference.first": "{\"kind\":\"OAuthRedirectReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"Route\",\"name\":\"jenkins\"}}"`
