### ISSUE TITLE
Allow configuration of basic auth password and client secret via a file

### ISSUE THREAD

**Issue by jcantrill** [openshift/oauth-proxy#54]
It would be useful to add switches such that the basic-auth-password and the client-secret were configured with a file instead of only plain-text.

**Comment by mrogers950** [comment]
I think in this case it would suffice to use --config rather than command line switches.

**Comment by jcantrill** [comment]
@simo5 how do we prioritize this to resolve https://bugzilla.redhat.com/show_bug.cgi?id=1570854

**Comment by jcantrill** [comment]
Resolvable with:
`--config` switch and https://github.com/openshift/oauth-proxy/blob/master/contrib/oauth-proxy.cfg.example
