### ISSUE TITLE
Unable to login to application behind oauth-proxy

### ISSUE THREAD

**Issue by xxwassyxx** [openshift/oauth-proxy#55]
Currently I am getting a 504 when trying to login to applications that live behind the oauth proxy.

My current logs from the proxy

```
2018/02/15 20:41:43 provider.go:476: Performing OAuth discovery against https://192.168.0.1/.well-known/oauth-authorization-server
--
  | 2018/02/15 20:41:43 provider.go:522: 200 GET https://192.168.0.1/.well-known/oauth-authorization-server  {
  | "issuer": "https://west.aws.openshift.bestbuy.com ",
  | "authorization_endpoint": "https://west.openshift.com/oauth/authorize ",
  | "token_endpoint": "https://west.openshift.com/oauth/token ",
  | "scopes_supported": [
  | "user:check-access",
  | "user:full",
  | "user:info",
  | "user:list-projects",
  | "user:list-scoped-projects"
  | ],
  | "response_types_supported": [
  | "code",
  | "token"
  | ],
  | "grant_types_supported": [
  | "authorization_code",
  | "implicit"
  | ],
  | "code_challenge_methods_supported": [
  | "plain",
  | "S256"
  | ]
  | }
  | 2018/02/15 20:41:43 provider.go:265: Delegation of authentication and authorization to OpenShift is enabled for bearer tokens and client certificates.
  | 2018/02/15 20:41:43 oauthproxy.go:161: mapping path "/" => upstream "http://localhost:9090 "
  | 2018/02/15 20:41:43 oauthproxy.go:184: compiled skip-auth-regex => "^/metrics"
  | 2018/02/15 20:41:43 oauthproxy.go:190: OAuthProxy configured for  Client ID: system:serviceaccount:openshift-metrics:prometheus
  | 2018/02/15 20:41:43 oauthproxy.go:200: Cookie settings: name:_oauth_proxy secure(https):true httponly:true expiry:168h0m0s domain:<default> refresh:disabled
  | 2018/02/15 20:41:43 http.go:96: HTTPS: listening on [::]:8443
  | 2018/02/15 21:00:06 oauthproxy.go:657: 10.129.0.1:56400 Cookie "_oauth_proxy" not present
  | 2018/02/15 21:00:06 provider.go:345: authorizer reason: User "system:anonymous" cannot get namespaces in project "openshift-metrics"
  | 2018/02/15 21:00:07 oauthproxy.go:657: 10.128.0.1:52578 Cookie "_oauth_proxy" not present
  | 2018/02/15 21:00:07 provider.go:345: authorizer reason: User "system:anonymous" cannot get namespaces in project "openshift-metrics"
  | 2018/02/15 21:00:39 oauthproxy.go:657: 10.128.0.1:53120 Cookie "_oauth_proxy" not present
  | 2018/02/15 21:00:39 provider.go:345: authorizer reason: User "system:anonymous" cannot get namespaces in project "openshift-metrics"
```

What I am seeing is that the discovery is using masterPublicURL instead of masterURL. Our public url is not acessable from within the cluster as the nodes sit on a private subnet and use masterURL.

So then I looked at trying to override the values given, but it seems that setting a login url only sets a endpoint not the actual url. Similar to redeem etc.

To check that it is because it uses the masterPublicURL instead of the masterURL I whitelisted the NAT on our masters and everything works as expected. So my question, is there a plan to make those fields to be over written?

**Comment by enj** [comment]
> is there a plan to make those fields to be over written?

No, there are no plans to change the configuration of these fields.  `masterPublicURL` must be available both internally and externally to the cluster.  The decision between `masterPublicURL` and `masterURL` is one that should be based on the origin of the request (and we did not have a good way to determine that), not one that is based on a singular hard coded configuration.  Thus we opted to use `masterPublicURL` as that is generally available to all parties.

If you have a proxy in front of openshift, you can have it override the data returned for `/.well-known/oauth-authorization-server` with the desired values.

**Comment by enj** [comment]
Feel free to reopen if you have further questions.

**Comment by xxwassyxx** [comment]
Not to re-open more of something on the side. I finally got this working using the below extra options
'-redeem-url=https://openshift.default.svc/oauth/token'
'-validate-url=https://openshift.default.svc/oauth/authorize'

So login is still on the public master url, but actual authentication is now on the internal where the nodes can actually hit the master api.
Working on a separate 500 error issue now but getting there.

**Comment by xxwassyxx** [comment]
Correction finally got it to work and here is my options.

```
- '-openshift-review-url=https://openshift.default.svc/apis/authorization.openshift.io/v1/subjectaccessreviews'
- '-redeem-url=https://openshift.default.svc/oauth/token'
- '-validate-url=https://openshift.default.svc/apis/user.openshift.io/v1/users/~'
```

**Comment by geropizarro** [comment]
The above worked for me too. Thanks!

**Comment by newlight77** [comment]
That works for me as well. Thanks
