### ISSUE TITLE
Prometheus oauth-proxy throws 'ErrorPage 500 Internal Error' using a signed certificate from a CA.

### ISSUE THREAD

**Issue by rflorenc** [openshift/oauth-proxy#56]
Summary:
Prometheus oauth-proxy throws 'ErrorPage 500 Internal Error' using a certificate signed from a CA.
Possibly related to [BZ1535585](https://bugzilla.redhat.com/show_bug.cgi?id=1535585)

Description:
When a user logs in via the webconsole and tries to access the prometheus route, he is redirected to the oauth-proxy login page which then throws a 500 internal error at login time.

Is there a recommended way of getting custom signed certs (ie from a CA) trusted at the cluster level?
Instead of having to configure it per component/client?

oc v3.7.23                                 
kubernetes v1.7.6+a08f5eeb62               
features: Basic-Auth GSSAPI Kerberos SPNEGO
                          
Server https://a.example.domain:8443
openshift v3.7.23                          
kubernetes v1.7.6+a08f5eeb62       

 
`oc describe sts prometheus`
// prom-proxy  
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus
      name: prometheus
    spec:
      containers:
      - args:
        - -provider=openshift
        - -https-address=:8443
        - -http-address=
        - -email-domain=*
        - -upstream=http://localhost:9090
        - -ssl-insecure-skip-verify
        - -client-id=system:serviceaccount:openshift-metrics:prometheus
        - '-openshift-sar={"resource": "namespaces", "verb": "get", "resourceName":
          "openshift-metrics", "namespace": "openshift-metrics"}'
        - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get",
          "resourceName": "openshift-metrics", "namespace": "openshift-metrics"}}'
        - -tls-cert=/etc/tls/private/tls.crt
        - -tls-key=/etc/tls/private/tls.key
        - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
        - -cookie-secret-file=/etc/proxy/secrets/session_secret
        - -openshift-ca=/etc/pki/tls/cert.pem
        - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - -skip-auth-regex=^/metrics
        image: registry.access.redhat.com/openshift3/oauth-proxy:v3.7
        imagePullPolicy: IfNotPresent
        name: prom-proxy
        ports:
        - containerPort: 8443
          name: web

`oc logs prometheus-0 -c prom-proxy -f`

2018/02/21 15:40:23 provider.go:476: Performing OAuth discovery against https://172.30.0.1/.well-known/oauth-authorization-server
2018/02/21 15:40:23 provider.go:522: 200 GET https://172.30.0.1/.well-known/oauth-authorization-server {
  "issuer": "https://a.example.domain:8443",
  "authorization_endpoint": "https://a.example.domain:8443/oauth/authorize",
  "token_endpoint": "https://a.example.domain:8443/oauth/token",
  "scopes_supported": [
    "user:check-access",
    "user:full",
    "user:info",
    "user:list-projects",
    "user:list-scoped-projects"
  ],
  "response_types_supported": [
    "code",
    "token"
  ],
  "grant_types_supported": [
    "authorization_code",
    "implicit"
  ],
  "code_challenge_methods_supported": [
    "plain",
    "S256"
  ]
}

2018/02/21 15:40:23 provider.go:265: Delegation of authentication and authorization to OpenShift is enabled for bearer tokens and client certificates.
2018/02/21 15:40:23 oauthproxy.go:161: mapping path "/" => upstream "http://localhost:9090"
2018/02/21 15:40:23 oauthproxy.go:184: compiled skip-auth-regex => "^/metrics"
2018/02/21 15:40:23 oauthproxy.go:190: OAuthProxy configured for  Client ID: system:serviceaccount:openshift-metrics:prometheus
2018/02/21 15:40:23 oauthproxy.go:200: Cookie settings: name:_oauth_proxy secure(https):true httponly:true expiry:168h0m0s domain:<default> refresh:disabled
2018/02/21 15:40:23 http.go:96: HTTPS: listening on [::]:8443
2018/02/21 15:42:29 oauthproxy.go:657: 10.1.2.1:52904 Cookie "_oauth_proxy" not present
2018/02/21 15:42:29 provider.go:345: authorizer reason: User "system:anonymous" cannot get namespaces in project "openshift-metrics"
2018/02/21 15:42:29 oauthproxy.go:657: 10.1.2.1:52904 Cookie "_oauth_proxy" not present
2018/02/21 15:42:29 provider.go:345: authorizer reason: User "system:anonymous" cannot get namespaces in project "openshift-metrics"
2018/02/21 15:43:46 oauthproxy.go:582: error redeeming code (client:10.1.2.1:53068): Post https://a.example.domain:8443/oauth/token: x509: certificate signed by unknown authority
2018/02/21 15:43:46 oauthproxy.go:399: ErrorPage 500 Internal Error Internal Error
2018/02/21 15:43:46 oauthproxy.go:657: 10.1.2.1:53068 Cookie "_oauth_proxy" not present
2018/02/21 15:43:46 provider.go:345: authorizer reason: User "system:anonymous" cannot get namespaces in project "openshift-metrics"
2018/02/21 15:43:54 oauthproxy.go:657: 10.1.2.1:53068 Cookie "_oauth_proxy" not present
2018/02/21 15:43:54 provider.go:345: authorizer reason: User "system:anonymous" cannot get namespaces in project "openshift-metrics"
2018/02/21 15:43:58 oauthproxy.go:582: error redeeming code (client:10.1.2.1:53068): Post https://a.example.domain:8443/oauth/token: x509: certificate signed by unknown authority
2018/02/21 15:43:58 oauthproxy.go:399: ErrorPage 500 Internal Error Internal Error
2018/02/21 15:43:59 oauthproxy.go:657: 10.1.2.1:53068 Cookie "_oauth_proxy" not present
2018/02/21 15:43:59 provider.go:345: authorizer reason: User "system:anonymous" cannot get namespaces in project "openshift-metrics"  

`/etc/origin/master/master-config.yaml`
// using OpenIDIdentityProvider for Keycloak and named certificates.

oauthConfig:
  assetPublicURL: https://a.example.domain:8443/console/                                                         
  grantConfig:                                                                                                           
    method: auto                                                                                                         
  identityProviders:                                                                                                     
  - name: keycloak                                                                                                       
    challenge: true                                                                                                      
    login: true                                                                                                          
    provider:                                                                                                            
      apiVersion: v1                                                                                                     
      kind: OpenIDIdentityProvider                                                                                       
      ca: /opt/certs/BAGLRootCA04.crt                                                                                    
      clientID: openshift                                                                                                
      clientSecret: 2feccb92-fa45-4a79-93ff-3af21a408023                                                                 
      claims:                                                                                                            
        id:                                                                                                              
        - sub                                                                                                            
        preferredUsername:                                                                                               
        - preferred_username                                                                                             
        name:                                                                                                            
        - name                                                                                                           
        email:                                                                                                           
        - email                                                                                                          
      urls:                                                                                                              
        authorize: https://keycloak-a.apps.example.domain/auth/realms/openshift/protocol/openid-connect/auth     
        token: https://keycloak-a.apps.example.domain/auth/realms/openshift/protocol/openid-connect/token        
        userInfo: https://keycloak-a.apps.example.domain/auth/realms/openshift/protocol/openid-connect/userinfo                                                                           
  masterCA: ca-bundle.crt                                                                                                
  masterPublicURL: https://a.example.domain:8443                                                                 
  masterURL: https://cluster1.example.domain:8443                                                                
  sessionConfig:                                                                                                         
    sessionMaxAgeSeconds: 3600                                                                                           
    sessionName: ssn                                                                                                     
    sessionSecretsFile: /etc/origin/master/session-secrets.yaml                                                          
  tokenConfig:                                                                                                           
    accessTokenMaxAgeSeconds: 86400                                                                                      
    authorizeTokenMaxAgeSeconds: 500                                                                                     
pauseControllers: false                                                                                                  
policyConfig:                                                                                                            
  bootstrapPolicyFile: /etc/origin/master/policy.json                                                                    
  openshiftInfrastructureNamespace: openshift-infra                                                                      
  openshiftSharedResourcesNamespace: openshift  
  pauseControllers: false
policyConfig:
  bootstrapPolicyFile: /etc/origin/master/policy.json
  openshiftInfrastructureNamespace: openshift-infra
  openshiftSharedResourcesNamespace: openshift
projectConfig:
  defaultNodeSelector: ""
  projectRequestMessage: ""
  projectRequestTemplate: ""
  securityAllocator:
    mcsAllocatorRange: s0:/2
    mcsLabelsPerProject: 5
    uidAllocatorRange: 1000000000-1999999999/10000
routingConfig:
  subdomain: apps.example.domain
serviceAccountConfig:
  limitSecretReferences: false
  managedNames:
  - default
  - builder
  - deployer
  masterCA: ca-bundle.crt
  privateKeyFile: serviceaccounts.private.key
  publicKeyFiles:
  - serviceaccounts.public.key
servingInfo:
  bindAddress: 0.0.0.0:8443
  bindNetwork: tcp4
  certFile: master.server.crt
  clientCA: ca.crt
  keyFile: master.server.key
  maxRequestsInFlight: 500
  namedCertificates:
  - certFile: /etc/origin/master/named_certificates/a.example.domain.cer
    keyFile: /etc/origin/master/named_certificates/nonprod.key
    names:
    - a.example.domain
  requestTimeoutSeconds: 3600
volumeConfig:
  dynamicProvisioningEnabled: true
  

@simo5

**Comment by rflorenc** [comment]
Fixed the client side x509 issue.
```
2018/02/21 15:43:46 oauthproxy.go:582: error redeeming code (client:10.1.2.1:53068): Post https://a.example.domain:8443/oauth/token: x509: certificate signed by unknown authority
2018/02/21 15:43:46 oauthproxy.go:399: ErrorPage 500 Internal Error Internal Error
```
Problem was that the cert chain in the browser was incomplete.


Now I keeping getting: 
```
oauthproxy.go:657 x.x.x.x:5xxxx Cookie "_oauth_proxy" not present
```

Any thoughts? bearer token / sa related?

**Comment by mrogers950** [comment]
@rflorenc that is just logged whenever you authenticate without a cookie. It's caused some confusion so we should probably change or remove it.

**Comment by rflorenc** [comment]
@mrogers950 thanks.

**Comment by fuxes** [comment]
@rflorenc Could you please give more detailed information about how you solved the issue? I'm facing the same problem.

**Comment by rflorenc** [comment]
You have to mount in your CA root certificate and then add an entry for `-openshift-ca=/certs/your-ca.pem`. If I remember correctly by editing the project ConfigMap.

When the proxy tries to hit the API as in:

```
018/07/11 05:28:22 provider.go:522: 201 POST https://nonprod1.test.evil.corp.us:8443/apis/authorization.openshift.io/v1/subjectaccessreviews  {"kind":"SubjectAccessReviewResponse","apiVersion":"authorization.openshift.io/v1","namespace":"dummy-uat","allowed":true,"reason":"allowed by openshift authorizer"}
2018/07/11 05:28:22 oauthproxy.go:612: 10.2.2.1:36804 authentication complete Session{userx@cluster.local token:true}
```

It throws the `x509: certificate signed by unknown authority` error because the CA that signed nonprod1.test.evil.corp.us is not trusted. 

Adding the CA Root from `/opt/certs/RootCA04.crt` (from `nonprod1`) solved this.

**Comment by rflorenc** [comment]
If you are troubleshooting and/or don't have the certs, you can use the - -skip-auth-regex= arg and add the endpoints you need.

example:
```
- -skip-auth-regex=^/graph.*
- -skip-auth-regex=^/targets
- -skip-auth-regex=^/status
- -skip-auth-regex=^/config
- -skip-auth-regex=^/
```
Obviously not for prod :)

btw, `- -ssl-insecure-skip-verify` doesn't work.

**Comment by sspreitzer** [comment]
Did you also find out how to solve this from an openshift-ansible point of view?
Is openshift_additional_ca a working option?

**Comment by sspreitzer** [comment]
I am trying that at the moment, to solve prometheus, kibana and maybe others from a central spot. Will keep you posted.

**Comment by sspreitzer** [comment]
@rflorenc openshift_additional_ca solved the problem as well!

Define openshift_additional_ca in your openshift-ansible inventory file with your CA or intermediate CA and it will work!

**Comment by rflorenc** [comment]
Good to know!
