### ISSUE TITLE
Fix description

### ISSUE THREAD

**Issue by discordianfish** [openshift/oauth-proxy#58]
The description says "A reverse proxy that provides authentication with OpenShift and **other OAuth providers**", but it's only supporting openshift it seems. Bummer..

**Comment by mrogers950** [comment]
@discordianfish I'm not sure exactly which description you are referring to, but the README should make it clear this is an OpenShift specific fork. If you need an OAuth proxy for other providers you should check out the project it was forked from https://github.com/bitly/oauth2_proxy

**Comment by discordianfish** [comment]
@mrogers950 The description of the repo itself on Github: "A reverse proxy that provides authentication with OpenShift and other OAuth providers"

**Comment by mrogers950** [comment]
@discordianfish Oh! Thanks, we will fix that.

**Comment by enj** [comment]
@smarterclayton fixed it.
