### ISSUE TITLE
Prevent proxy from starting if the SA does not match

### ISSUE THREAD

**Issue by enj** [openshift/oauth-proxy#61]
We get the SA name as user input, and process it here:

https://github.com/openshift/oauth-proxy/blob/a95fc9fcd199535f3c240642f955f37130d35c18/providers/openshift/provider.go#L94-L105

This code assumes the SA provided by user input is the same one that is running the pod (because we use that as the secret for the SA based OAuth client).  It pulls the SA namespace from this as well.

We need to validate this instead of assuming the values are in agreement.  We could do `oc get user ~` with the SA token to make sure it matches (but I feel like there must be a better way to tell what SA is running a pod from inside the pod).  The more correct thing would be a flag like `--use-openshift-service-account=bool` that just pulls the correct information from the pod / API.

xref: #60

**Comment by mrogers950** [comment]
@enj This sounds like a good idea to me.

**Comment by jparrill** [comment]
+1
