### ISSUE TITLE
Merge back with upstream?

### ISSUE THREAD

**Issue by discordianfish** [openshift/oauth-proxy#63]
Hi,

the upstream version doesn't support certain features and doesn't look well maintained in general with lots of stale pull requests. This project on the other hand doesn't support the most common oauth providers. It would be great to merge back. Specifically this could mean adding back the providers from the upstream project. I'm happy to help with this if you want to go down that route.

**Comment by enj** [comment]
If anything, I plan on removing any of remnants of the upstream code to minimize this repo.  It is hard to reason about because it has many pointless abstractions.

It exists to provide OAuth via the Openshift infrastructure it is running on.  There are no plans to support other providers.

**Comment by simo5** [comment]
@discordianfish if the original repo becomes more alive we may consider merging back eventually.
But at the moment we do not have the resources for a costly syncback, and prefer to nail down all the details we need to get right for tight Openshift integration.
I'm sorry that we cannot more positively act on your suggestion at this time.

**Comment by discordianfish** [comment]
Then I'll have to maintain the 3rd fork of the proxy with the fixes from this repo and the providers from the upstream repo.. I find this fragmentation quite unfortunate to say at least.

**Comment by discordianfish** [comment]
To be clear: I'd propose to make *this* the "generic oauth proxy" by adding back the providers. I have a branch which appears to be working (although I still need to fix the tests): https://github.com/discordianfish/oauth2_proxy/commits/add-providers-from-upstream
