### ISSUE TITLE
Can my app reuse a token for requests to itself?

### ISSUE THREAD

**Issue by kargakis** [openshift/oauth-proxy#65]
I am running an application behind an oauth proxy that needs to make requests back to itself (frontend needs to talk to backend, both exposed as public endpoints). How can I authenticate the request from the frontend to the backend?

**Comment by enj** [comment]
Only with the delegate URL (remote auth) setup (not the OAuth flow).  Give the SA running the proxy the correct permissions needed for the specific URL.

**Comment by kargakis** [comment]
What exactly should I do? The sa has the correct permissions already
```
$ oc policy can-i get cm -n ci --as=system:serviceaccount:ci:tracer
yes
```
I have configured a delegate URL in the pod template like so:
```
        - '-openshift-delegate-urls={"/trace": {"resource": "configmaps", "verb":
          "get", "namespace":"ci"}}'
```
but the request from the frontend to the backend is still interpreted as an anonymous request and gets rejected.
```
2018/03/11 20:44:05 provider.go:347: authorizer reason: User "system:anonymous" cannot get configmaps in project "ci"
```

**Comment by enj** [comment]
How is that request being made?  It needs to include the service account's bearer token in the authorization header.

**Comment by kargakis** [comment]
Yeah, the frontend does not set any header in its requests today. I need to figure out how to put the token in the frontend.

**Comment by stevekuznetsov** [comment]
We needed to pass the cookies.
/close

**Comment by stevekuznetsov** [comment]
https://github.com/kubernetes/test-infra/pull/7391
