### ISSUE TITLE
504 timeout after logging in

### ISSUE THREAD

**Issue by david-rh** [openshift/oauth-proxy#66]
I was attempting to deploy syndesis to openshift. This project uses oauth-proxy. When I access the service, I run into a 504 timeout after logging in.  I am using RH-SSO for my openshift authentication. And in the logs for the oauthproxy I am seeing the following error:

2018/04/04 17:58:00 oauthproxy.go:635: error redeeming code (client:10.128.0.1:34586): Post https://rhsledcloud.net:8443/oauth/token: dial tcp 13.59.116.22:8443: getsockopt: connection timed out

Any idea on what I might be missing in my setup for this to work.

**Comment by enj** [comment]
The proxy is unable to reach the `token_endpoint` of the API master.  You will need to make sure that is both internally and externally routeable.

```
$ oc get --raw /.well-known/oauth-authorization-server
```

```json
{
  "issuer": "https://10.13.129.2:8443",
  "authorization_endpoint": "https://10.13.129.2:8443/oauth/authorize",
  "token_endpoint": "https://10.13.129.2:8443/oauth/token",
  "scopes_supported": [
    "user:check-access",
    "user:full",
    "user:info",
    "user:list-projects",
    "user:list-scoped-projects"
  ],
  "response_types_supported": [
    "code",
    "token"
  ],
  "grant_types_supported": [
    "authorization_code",
    "implicit"
  ],
  "code_challenge_methods_supported": [
    "plain",
    "S256"
  ]
}
```

**Comment by david-rh** [comment]
Thanks, it looks like that is the issue.  It's using the public dns name of my ocp master.  But, for some reason, I can't reach out from with in the pod.  I can't even ping the public ip, only the private ip.  I also notic that I can't ping anything else, such as google, from inside my pods.  I'm not sure why this is, if you have any suggestions on what might be the problem I would appreciate the guidance.
