### ISSUE TITLE
Access to openshift origin-aggregated-logging (Elasticsearch exposed by oauth2) from a client

### ISSUE THREAD

**Issue by yeplaa** [openshift/oauth-proxy#72]
Hello,

I need to connect openshift origin-aggregated-logging (Elasticsearch exposed by oauth2) from a client that no supports oauth authentication. Can the oauth-proxy play this proxy role to transfer the stream from the client and add the bearer oauth to transfer to the elasticsearch in https?

Thank's
Loïc

**Comment by mrogers950** [comment]
@yeplaa I'm not certain what you mean by the client not supporting oauth.. It would need to be able to set Basic/Bearer Authorization headers. After authenticating to OpenShift a bearer token is returned and used by the client to access the protected upstream service, and this token can also be optionally passed to the upstream service with the flag `-pass-user-bearer-token`.

**Comment by yeplaa** [comment]
@mrogers Thank's for your reply.  When i talk about  "the client not supporting oauth", it's an application client in a container (in Openshift environment) that isn't able natively to set Bearer Authorization headers in this requests to the another application in a container (Elasticsearch exposed by oauth2) 
 
When i use the  pass-user-bearer-token option in oauth-proxy, i have the error :  
flag provided but not defined: -pass-user-bearer-token

Do you have a idea?

Thank's

**Comment by simo5** [comment]
@yeplaa can the client do basic auth ? or any other kind of auth ? or is your client incapable of any auth ?

**Comment by yeplaa** [comment]
@simo5 The client supports only basic auth but no any auth as oauth.

**Comment by simo5** [comment]
Premise: oauth-proxy is normally used to protect applications that do not know/want to handle authentication, not the other way around.
That said if your client can do basic auth, then maybe you can try the -htpasswd-file option ?

**Comment by yeplaa** [comment]
@simo5  Thank's for your reply. Origin-aggregated-logging (Elasticsearch exposed by oauth2) support only Oauth. It's good with nginx. Good day
