### ISSUE TITLE
'authenticated-emails-file' option not respected by default

### ISSUE THREAD

**Issue by thirdeyenick** [openshift/oauth-proxy#83]
Hi,
I just tested the oauth-proxy in a simple application. I used the --authenticated-emails-file option. After testing access I noticed that all email addresses are allowed, so you just need to have a valid openshift account. Although this is documented I still think that just passing the 'authenticated-emails-file' should give the expected result of just allowing the given addresses.

I had a look into the code and found that by default all domains ('*') are allowed, not respecting any given 'authenticated-emails-file' option (options.go line 165). Maybe we could check there if an authenticated-emails-file option was given and if yes just do a
```golang
o.EmailDomains = []string{}
```
?

**Comment by mrogers950** [comment]
We're planning on drastically trimming this project down to the essential OpenShift pieces, namely the login flow, bearer token flow, and SAR-based authz. So this will be one of the options we inherited from the oauth2_proxy fork that that we will get rid of rather than implement. Sorry for the inconvenience.

**Comment by thirdeyenick** [comment]
Thanks for the information. Is it possible to 'simulate' the email functionality with SAR somehow?

**Comment by enj** [comment]
I suppose if you just want some set of users to be able to login, you could still use the SAR flow:

1. Create a new empty project
2. Create a role that does something trivial and safe like `get configmap with name allow-app-access`
3. Give the appropriate users that access via a role binding
4. Have OAuth proxy use that get as the SAR check
