### ISSUE TITLE
-tls-client-ca seems completely dead

### ISSUE THREAD

**Issue by jim-minter** [openshift/oauth-proxy#87]
I can't get TLS client authentication to work.  Setting -tls-client-ca causes oauth-proxy to request a client cert, but it then does nothing with it.  Code inspection suggests to me that it might have worked after PR #1, but that it hasn't since PR #2.  I can't see any code in master which checks the peer cert in any way.

This is a pity, because it would be really useful if we supported TLS client authentication.

@mrogers950 @simo5

**Comment by jim-minter** [comment]
@mjudeikis

**Comment by mjudeikis** [comment]
@jim-minter where did you do this"?

**Comment by mrogers950** [comment]
@jim-minter It appears that the client cert check was removed in favor of bearer token auth , but the option was left alone. It would not be difficult to add back in but I'm unsure if we want to.  
If we added it back it should probably be an additional check to bearer token auth and not an override.
@simo5 @enj your thoughts?

**Comment by enj** [comment]
@jim-minter try to set the `client-ca-file` option instead.

**Comment by mrogers950** [comment]
@jim-minter @mjudeikis this feature works but at the moment you actually have to set both --client-ca-file and --tls-client-ca together. 
- --client-ca-file=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
- --tls-client-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt 
The --tls-client-ca option enables oauth-proxy to request the cert as you noticed, but separately --client-ca-file enables cert validation in the authenticator. We will need to fix this.

**Comment by mrogers950** [comment]
#89
