### ISSUE TITLE
Routing to an external route

### ISSUE THREAD

**Issue by pramodhkp** [openshift/oauth-proxy#90]
Is it possible to route to an external pod instead of a sidecar using oauth-proxy? I would like to use it as a standalone container and route to other pods/services in a different namespace in the cluster.

**Comment by mrogers950** [comment]
@pramodhkp Yes, there's no explicit requirement for it to be a sidecar, so you can set --upstream to point wherever you need.

**Comment by pramodhkp** [comment]
@mrogers950 Thanks for the quick reply! I will try that.
