### ISSUE TITLE
Getting "The client is not authorized to request a token using this method"

### ISSUE THREAD

**Issue by jpkrohling** [openshift/oauth-proxy#95]
I'm trying to integrate the OpenShift OAuth Proxy with the Jaeger Operator, but I'm currently unable to login as `developer`:`developer`. Upon login, this is what I see in the browser:

![image](https://user-images.githubusercontent.com/13387/48210386-895d3300-e377-11e8-839c-1cfe6c29a5b4.png)

In the container logs, this can be seen:

```
$ oc logs simplest-6fb4f96f96-kwwng -c oauth-proxy
2018/11/08 15:48:34 provider.go:102: Defaulting client-id to system:serviceaccount:default:simplest-ui-proxy
2018/11/08 15:48:34 provider.go:107: Defaulting client-secret to service account token /var/run/secrets/kubernetes.io/serviceaccount/token
2018/11/08 15:48:34 provider.go:530: Performing OAuth discovery against https://172.30.0.1/.well-known/oauth-authorization-server
2018/11/08 15:48:34 provider.go:576: 200 GET https://172.30.0.1/.well-known/oauth-authorization-server {
  "issuer": "https://192.168.42.155:8443",
  "authorization_endpoint": "https://192.168.42.155:8443/oauth/authorize",
  "token_endpoint": "https://192.168.42.155:8443/oauth/token",
  "scopes_supported": [
    "user:check-access",
    "user:full",
    "user:info",
    "user:list-projects",
    "user:list-scoped-projects"
  ],
  "response_types_supported": [
    "code",
    "token"
  ],
  "grant_types_supported": [
    "authorization_code",
    "implicit"
  ],
  "code_challenge_methods_supported": [
    "plain",
    "S256"
  ]
}
2018/11/08 15:48:34 oauthproxy.go:201: mapping path "/" => upstream "http://localhost:16686/"
2018/11/08 15:48:34 oauthproxy.go:228: OAuthProxy configured for  Client ID: system:serviceaccount:default:simplest-ui-proxy
2018/11/08 15:48:34 oauthproxy.go:238: Cookie settings: name:_oauth_proxy secure(https):true httponly:true expiry:168h0m0s domain:<default> refresh:disabled
2018/11/08 15:48:34 http.go:56: HTTP: listening on 127.0.0.1:4180
2018/11/08 15:48:34 http.go:96: HTTPS: listening on [::]:8443
2018/11/08 15:49:05 oauthproxy.go:635: error redeeming code (client:172.17.0.1:43104): got 400 from "https://192.168.42.155:8443/oauth/token" {"error":"unauthorized_client","error_description":"The client is not authorized to request a token using this method."}
2018/11/08 15:49:05 oauthproxy.go:434: ErrorPage 500 Internal Error Internal Error
```

This is how the service account looks like in Go (I can provide the YAML version as well, if necessary):

https://github.com/jpkrohling/jaeger-operator/blob/89-Protect-ui-with-OAuth-Proxy/pkg/account/oauth-proxy.go

I'm not sure it's relevant, but this is how the sidecar container looks like:

https://github.com/jpkrohling/jaeger-operator/blob/89-Protect-ui-with-OAuth-Proxy/pkg/inject/oauth-proxy.go#L32

Any ideas on what I might be doing wrong?

**Comment by mrogers950** [comment]
@jpkrohling You should make sure that the SA on the deployment and config are set and in agreement: see 
https://github.com/openshift/oauth-proxy/blob/master/contrib/sidecar.yaml#L50 and
https://github.com/openshift/oauth-proxy/blob/master/contrib/sidecar.yaml#L61
If you leave the deployment spec serviceAccountName out, by default the pod may not be running with the same SA and you would get this error.

**Comment by jpkrohling** [comment]
That was it, thanks!
